### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by skirkpatrick** [skirkpatrick/svc#1]
There is no readme. There should be. Should explain ideology as well as setup instructions. A license would probably be good at some point, too.

**Comment by russplaysguitar** [comment]
:+1: I want to show this to people but there isn't much besides code to show!

**Comment by skirkpatrick** [comment]
You're 100% correct! Working on README right now ;D

**Comment by skirkpatrick** [comment]
Added as of bd923af6eabe676af694ca17c0c6f9e2bd80f30b
